id: IEAD3EBED
ocr_import_info:
  timestamp: '2023-09-29T16:05:27.404019+00:00'
  batch_id: batch-bf8d
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 17:38:29.539401+00:00
last_modified: 2023-09-29 17:38:29.539407+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W321
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW321
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཚད་མ་རྣམ་འགྲེལ་གྱི་ཊཱིཀ་ཆེན་རིགས་པའི་རྒྱ་མཚོ།
  languages:
  - bo
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.9933147052905282
  ocr_word_median_confidence_index: 0.9999999
bases:
  I1KG8605:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8605
      total_pages: 549
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG8605.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9929827818023118
  I1KG8606:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG8606
      total_pages: 604
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG8606.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.993617395159366
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
